# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/grandprimeve3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/grandprimeve3g/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
    vendor/samsung/grandprimeve3g/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/hw/lights.sc8830.so:system/lib/hw/lights.sc8830.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/lib_SamsungRec_V03010.so:system/lib/lib_SamsungRec_V03010.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libjpega.so:system/lib/libjpega.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_gsmdec.so:system/lib/libstagefright_soft_gsmdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_vpxenc.so:system/lib/libstagefright_soft_vpxenc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_h264dec.so:system/lib/libstagefright_soft_h264dec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_h264enc.so:system/lib/libstagefright_soft_h264enc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_hevcdec.so:system/lib/libstagefright_soft_hevcdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_mjpgdec.so:system/lib/libstagefright_soft_mjpgdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_opusdec.so:system/lib/libstagefright_soft_opusdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libstagefright_soft_imaadpcmdec.so:system/lib/libstagefright_soft_imaadpcmdec.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/grandprimeve3g/proprietary/usr/share/alsa/alsa.conf:system/usr/share/alsa/alsa.conf \
    vendor/samsung/grandprimeve3g/proprietary/vendor/firmware/BCM43430A1_V0025.0070.hcd:system/vendor/firmware/BCM43430A1_V0025.0070.hcd \
    vendor/samsung/grandprimeve3g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/grandprimeve3g/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/grandprimeve3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/grandprimeve3g/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_avcdec_hw_sprd.so:system/lib/libomx_avcdec_hw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_avcdec_sw_sprd.so:system/lib/libomx_avcdec_sw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_avcenc_hw_sprd.so:system/lib/libomx_avcenc_hw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_m4vh263dec_hw_sprd.so:system/lib/libomx_m4vh263dec_hw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_m4vh263dec_sw_sprd.so:system/lib/libomx_m4vh263dec_sw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_m4vh263enc_hw_sprd.so:system/lib/libomx_m4vh263enc_hw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/lib/libomx_vpxdec_hw_sprd.so:system/lib/libomx_vpxdec_hw_sprd.so \
    vendor/samsung/grandprimeve3g/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/grandprimeve3g/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/grandprimeve3g/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/grandprimeve3g/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/grandprimeve3g/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/grandprimeve3g/proprietary/etc/audio_para:system/etc/audio_para \
    vendor/samsung/grandprimeve3g/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/grandprimeve3g/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml \
    vendor/samsung/grandprimeve3g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/grandprimeve3g/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/grandprimeve3g/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/grandprimeve3g/proprietary/etc/slog.conf:system/etc/slog.conf \
    vendor/samsung/grandprimeve3g/proprietary/etc/slog.conf.user:system/etc/slog.conf.user \
    vendor/samsung/grandprimeve3g/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml \
    vendor/samsung/grandprimeve3g/proprietary/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/grandprimeve3g/proprietary/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/grandprimeve3g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/grandprimeve3g/proprietary/bin/atrace:system/bin/atrace \
    vendor/samsung/grandprimeve3g/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/grandprimeve3g/proprietary/bin/cpu:system/bin/cpu \
    vendor/samsung/grandprimeve3g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/grandprimeve3g/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/grandprimeve3g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/grandprimeve3g/proprietary/bin/sensorservice:system/bin/sensorservice \
    vendor/samsung/grandprimeve3g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/grandprimeve3g/proprietary/bin/slog:system/bin/slog \
    vendor/samsung/grandprimeve3g/proprietary/bin/slogctl:system/bin/slogctl \
    vendor/samsung/grandprimeve3g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/grandprimeve3g/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/grandprimeve3g/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/grandprimeve3g/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/grandprimeve3g/proprietary/bin/npsmobex:system/bin/npsmobex
